DROP DATABASE IF EXISTS medical_center_db;

CREATE DATABASE medical_center_db;

\c medical_center_db


CREATE TABLE "user" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "role" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "level" int NOT NULL
);

CREATE TABLE "user_entity" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "medical_center_doctor_id" bigint,
  "medical_center_patient_id" bigint
);

CREATE TABLE "user_notification" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "message" varchar NOT NULL,
  "message_state" varchar NOT NULL
);

CREATE TABLE "doctor_notification" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" bigint,
  "message" varchar NOT NULL,
  "message_state" varchar NOT NULL
);

CREATE TABLE "patient_notification" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" bigint,
  "message" varchar NOT NULL,
  "message_state" varchar NOT NULL
);

CREATE TABLE "user_entity_role" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_entity_id" bigint NOT NULL,
  "role_id" bigint NOT NULL
);

CREATE TABLE "medical_center" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "phone" varchar NOT NULL,
  "logo" varchar DEFAULT '',
  "is_active" boolean DEFAULT true
);

CREATE TABLE "medical_center_location" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medical_center_id" bigint NOT NULL,
  "name" varchar(255),
  "latitude" decimal(9,6),
  "longitude" decimal(9,6),
  "address" varchar(255),
  "city" varchar(255),
  "state" varchar(255),
  "country" varchar(255),
  "postal_code" varchar(20)
);

CREATE TABLE "medical_center_doctor" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medical_center_id" bigint NOT NULL,
  "doctor_id" bigint NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "medical_center_patient" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medical_center_id" bigint NOT NULL,
  "patient_id" bigint NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "appoitment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medical_center_doctor_id" bigint NOT NULL,
  "medical_center_patient_id" bigint NOT NULL,
  "appoitment_date" date NOT NULL,
  "start_time" time NOT NULL,
  "end_time" time NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "diagnosis" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appoitment_id" bigint NOT NULL,
  "disease_id" bigint NOT NULL,
  "date_of_diagnosis" date NOT NULL,
  "condition" varchar(50),
  "comment" varchar
);

CREATE TABLE "disease_category" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "disease" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "disease_category_id" bigint NOT NULL,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "speciality" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "doctor" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "gender_id" bigint NOT NULL,
  "date_of_birth" date NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "doctor_speciality" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" bigint NOT NULL,
  "speciality_id" bigint NOT NULL,
  "is_activ" boolean DEFAULT true
);

CREATE TABLE "patient" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "gender_id" bigint NOT NULL,
  "date_of_birth" date NOT NULL,
  "address" varchar(100) NOT NULL,
  "phone_number" varchar(20) NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "bill_state" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "patient_bill" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medical_center_patient_id" bigint NOT NULL,
  "diagnosis_id" bigint NOT NULL,
  "bill_state_id" bigint NOT NULL,
  "amont" decimal NOT NULL
);

CREATE TABLE "bills_payment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_bill_id" bigint NOT NULL,
  "amont" decimal NOT NULL,
  "date_payment" timestamp NOT NULL
);

CREATE TABLE "medical_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medical_center_patient_id" bigint NOT NULL,
  "medication_records_id" bigint NOT NULL,
  "treatment" varchar(100)
);

CREATE TABLE "medication_records" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "medical_center_patient_id" bigint NOT NULL,
  "diagnosis_id" bigint NOT NULL,
  "medication_name" varchar(50) NOT NULL,
  "dosage" varchar(20),
  "start_date" date,
  "end_date" date
);

CREATE TABLE "gender" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

ALTER TABLE "user_entity" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user_entity_role" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "user_entity_role" ADD FOREIGN KEY ("user_entity_id") REFERENCES "user_entity" ("id");

ALTER TABLE "user_notification" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "patient_notification" ADD FOREIGN KEY ("patient_id") REFERENCES "patient" ("id");

ALTER TABLE "medical_center_location" ADD FOREIGN KEY ("medical_center_id") REFERENCES "medical_center" ("id");

ALTER TABLE "medical_center_doctor" ADD FOREIGN KEY ("medical_center_id") REFERENCES "medical_center" ("id");

ALTER TABLE "medical_center_patient" ADD FOREIGN KEY ("medical_center_id") REFERENCES "medical_center" ("id");

ALTER TABLE "medical_center_patient" ADD FOREIGN KEY ("patient_id") REFERENCES "patient" ("id");

ALTER TABLE "medical_center_doctor" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("id");

ALTER TABLE "doctor_notification" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("id");

ALTER TABLE "disease" ADD FOREIGN KEY ("disease_category_id") REFERENCES "disease_category" ("id");

ALTER TABLE "doctor" ADD FOREIGN KEY ("gender_id") REFERENCES "gender" ("id");

ALTER TABLE "doctor_speciality" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("id");

ALTER TABLE "doctor_speciality" ADD FOREIGN KEY ("speciality_id") REFERENCES "speciality" ("id");

ALTER TABLE "patient" ADD FOREIGN KEY ("gender_id") REFERENCES "gender" ("id");

ALTER TABLE "bills_payment" ADD FOREIGN KEY ("patient_bill_id") REFERENCES "patient_bill" ("id");

ALTER TABLE "patient_bill" ADD FOREIGN KEY ("medical_center_patient_id") REFERENCES "medical_center_patient" ("id");

ALTER TABLE "patient_bill" ADD FOREIGN KEY ("diagnosis_id") REFERENCES "diagnosis" ("id");

ALTER TABLE "patient_bill" ADD FOREIGN KEY ("bill_state_id") REFERENCES "bill_state" ("id");

ALTER TABLE "medication_records" ADD FOREIGN KEY ("medical_center_patient_id") REFERENCES "medical_center_patient" ("id");

ALTER TABLE "medication_records" ADD FOREIGN KEY ("diagnosis_id") REFERENCES "diagnosis" ("id");

ALTER TABLE "medical_history" ADD FOREIGN KEY ("medical_center_patient_id") REFERENCES "medical_center_patient" ("id");

ALTER TABLE "medical_history" ADD FOREIGN KEY ("medication_records_id") REFERENCES "medical_center_doctor" ("id");

ALTER TABLE "appoitment" ADD FOREIGN KEY ("medical_center_doctor_id") REFERENCES "medical_center_doctor" ("id");

ALTER TABLE "appoitment" ADD FOREIGN KEY ("medical_center_patient_id") REFERENCES "medical_center_patient" ("id");

ALTER TABLE "diagnosis" ADD FOREIGN KEY ("appoitment_id") REFERENCES "appoitment" ("id");

ALTER TABLE "diagnosis" ADD FOREIGN KEY ("disease_id") REFERENCES "disease" ("id");

ALTER TABLE "user_entity" ADD FOREIGN KEY ("medical_center_doctor_id") REFERENCES "medical_center_doctor" ("id");

ALTER TABLE "user_entity" ADD FOREIGN KEY ("medical_center_patient_id") REFERENCES "medical_center_patient" ("id");
