DROP DATABASE IF EXISTS craigslist_db;

CREATE DATABASE craigslist_db;

\c craigslist_db




CREATE TABLE "user" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "region_id" bigint NOT NULL,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "phone" varchar(20),
  "is_active" boolean DEFAULT true
);

CREATE TABLE "region" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "category" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_id" bigint NOT NULL,
  "name" varchar(255) NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "post" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  "region_id" bigint NOT NULL,
  "title" varchar(255) NOT NULL,
  "description" varchar(255) NOT NULL,
  "address" varchar(255),
  "city" varchar(255),
  "street" varchar(255),
  "cross_street" varchar(255),
  "postal_code" varchar(20),
  "is_active" boolean DEFAULT true
);

ALTER TABLE "user" ADD FOREIGN KEY ("region_id") REFERENCES "region" ("id");

ALTER TABLE "category" ADD FOREIGN KEY ("type_id") REFERENCES "type" ("id");

ALTER TABLE "post" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "post" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");

ALTER TABLE "post" ADD FOREIGN KEY ("region_id") REFERENCES "region" ("id");
