DROP DATABASE IF EXISTS soccer_league_db;

CREATE DATABASE soccer_league_db;

\c soccer_league_db




CREATE TABLE "league" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "season" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "league_id" bigint NOT NULL,
  "league_season_name" varchar,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL
);

CREATE TABLE "season_ranking" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "season_id" bigint NOT NULL
);

CREATE TABLE "team" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "league_id" bigint NOT NULL,
  "name" varchar
);

CREATE TABLE "team_season_ranking" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "season_ranking_id" bigint NOT NULL,
  "team_id" bigint NOT NULL,
  "rank" varchar(2) NOT NULL
);

CREATE TABLE "player" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "team_id" bigint NOT NULL,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "gender_id" bigint NOT NULL,
  "date_of_birth" date NOT NULL
);

CREATE TABLE "referee_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "referee" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "gender_id" bigint NOT NULL,
  "date_of_birth" date NOT NULL
);

CREATE TABLE "game" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "team_one_id" bigint NOT NULL,
  "team_two_id" bigint NOT NULL,
  "game_date" date NOT NULL
);

CREATE TABLE "game_referee" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" bigint NOT NULL,
  "referee_id" bigint NOT NULL,
  "referee_type_id" bigint NOT NULL
);

CREATE TABLE "goal" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" bigint NOT NULL,
  "player_id" bigint NOT NULL,
  "score" int DEFAULT 1,
  "time" varchar(3) NOT NULL
);

CREATE TABLE "gender" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

ALTER TABLE "season" ADD FOREIGN KEY ("league_id") REFERENCES "league" ("id");

ALTER TABLE "season_ranking" ADD FOREIGN KEY ("season_id") REFERENCES "season" ("id");

ALTER TABLE "team" ADD FOREIGN KEY ("league_id") REFERENCES "league" ("id");

ALTER TABLE "team_season_ranking" ADD FOREIGN KEY ("season_ranking_id") REFERENCES "season_ranking" ("id");

ALTER TABLE "team_season_ranking" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "referee" ADD FOREIGN KEY ("gender_id") REFERENCES "gender" ("id");

ALTER TABLE "game" ADD FOREIGN KEY ("team_one_id") REFERENCES "team" ("id");

ALTER TABLE "game" ADD FOREIGN KEY ("team_two_id") REFERENCES "team" ("id");

ALTER TABLE "goal" ADD FOREIGN KEY ("game_id") REFERENCES "game" ("id");

ALTER TABLE "goal" ADD FOREIGN KEY ("player_id") REFERENCES "player" ("id");

ALTER TABLE "game_referee" ADD FOREIGN KEY ("game_id") REFERENCES "game" ("id");

ALTER TABLE "game_referee" ADD FOREIGN KEY ("referee_id") REFERENCES "referee" ("id");

ALTER TABLE "game_referee" ADD FOREIGN KEY ("referee_type_id") REFERENCES "referee_type" ("id");
