DROP DATABASE IF EXISTS air_traffic;

CREATE DATABASE air_traffic;

\c air_traffic



CREATE TABLE "airline" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "tickets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "travler_id" bigint NOT NULL,
  "airline_id" bigint NOT NULL,
  "seat" varchar(20) NOT NULL,
  "departure" TIMESTAMP NOT NULL,
  "arrival" TIMESTAMP NOT NULL,
  "from_city" varchar(20) NOT NULL,
  "from_country" varchar(20) NOT NULL,
  "to_city" varchar(20) NOT NULL,
  "to_country" varchar(20) NOT NULL,
  "flight_number" varchar NOT NULL
);

CREATE TABLE "travler" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(20) NOT NULL,
  "last_name" varchar(20) NOT NULL,
  "date_of_birth" date NOT NULL,
  "gender_id" bigint NOT NULL
);

CREATE TABLE "gender" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

ALTER TABLE "tickets" ADD FOREIGN KEY ("airline_id") REFERENCES "airline" ("id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("travler_id") REFERENCES "travler" ("id");

ALTER TABLE "travler" ADD FOREIGN KEY ("gender_id") REFERENCES "gender" ("id");
