DROP DATABASE IF EXISTS music;

CREATE DATABASE music;

\c music




CREATE TABLE "artists" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gender_id" bigint NOT NULL,
  "first_name" varchar(20) NOT NULL,
  "last_name" varchar(20) NOT NULL,
  "date_of_birth" date NOT NULL
);

CREATE TABLE "album_artists" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "artists_id" bigint NOT NULL,
  "album_id" bigint NOT NULL
);

CREATE TABLE "producers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "gender" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "album" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "date_album" date NOT NULL
);

CREATE TABLE "album_producers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producers_id" bigint NOT NULL,
  "album_id" bigint NOT NULL
);

CREATE TABLE "songs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "album_id" bigint NOT NULL,
  "title" varchar,
  "duration_in_seconds" int NOT NULL,
  "release_date" date NOT NULL
);

CREATE TABLE "artists_on_songs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "songs_id" bigint NOT NULL,
  "artists_id" bigint NOT NULL
);

ALTER TABLE "album_artists" ADD FOREIGN KEY ("artists_id") REFERENCES "artists" ("id");

ALTER TABLE "artists" ADD FOREIGN KEY ("gender_id") REFERENCES "gender" ("id");

ALTER TABLE "album_artists" ADD FOREIGN KEY ("album_id") REFERENCES "album" ("id");

ALTER TABLE "album_producers" ADD FOREIGN KEY ("producers_id") REFERENCES "producers" ("id");

ALTER TABLE "album_producers" ADD FOREIGN KEY ("album_id") REFERENCES "album" ("id");

ALTER TABLE "songs" ADD FOREIGN KEY ("album_id") REFERENCES "album" ("id");

ALTER TABLE "artists_on_songs" ADD FOREIGN KEY ("songs_id") REFERENCES "songs" ("id");

ALTER TABLE "artists_on_songs" ADD FOREIGN KEY ("artists_id") REFERENCES "artists" ("id");
